G | Include Jumpscare texturepack

diff --git a/.github/workflows/build_packs.yml b/.github/workflows/build_packs.yml
--- a/.github/workflows/build_packs.yml
+++ b/.github/workflows/build_packs.yml
@@ -11,6 +11,7 @@ on:
       - 'main/**'
       - 'sharders/**'
       - 'cosmetics/**'
+      - 'jumpscares/**'
 
 
   # Allows you to run this workflow manually from the Actions tab
@@ -75,6 +76,17 @@ jobs:
             jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
           done
 
+# Check the cosmetics folder for .json syntax / overall errors
+  validate_jumpscares:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Validate JSON Files - Cosmetics
+        run: |
+          cd jumpscares
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
 
 
 
@@ -191,7 +203,38 @@ jobs:
         run: |
          mc cp nikosnextbots_cosmetics.zip myminio/nnb/
 
+  # Build the jumpscares pack
+  build_jumpscares:
+    runs-on: ubuntu-latest
+    needs: [validate_jumpscares]
 
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v4
+      
+      - name: Setup MinIO
+        run: |
+          wget https://dl.min.io/client/mc/release/linux-amd64/mc
+          chmod +x mc
+          sudo mv mc /usr/local/bin/
+
+
+      - name: Set Up MinIO Configuration
+        run: |
+          mc alias set myminio https://mcapi.nikodaproot.pl/ "${{ secrets.MINIO_ACCESS_KEY }}" "${{ secrets.MINIO_SECRET_KEY }}"
+
+
+      - name: Prepare File
+        run: |
+         cd jumpscares
+         zip -r ../nikosnextbots_jumpscares.zip *
+
+
+      - name: Upload to Host
+        run: |
+         mc cp nikosnextbots_jumpscares.zip myminio/nnb/
 
 
 
@@ -257,7 +300,7 @@ jobs:
 
   push_texturepack:
     runs-on: ubuntu-latest
-    needs: [build_main, build_sharders, build_cosmetics]
+    needs: [build_main, build_sharders, build_cosmetics, build_jumpscares]
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
