Implement .json check into the build script

diff --git a/.github/workflows/build_packs.yml b/.github/workflows/build_packs.yml
--- a/.github/workflows/build_packs.yml
+++ b/.github/workflows/build_packs.yml
@@ -17,6 +17,55 @@ on:
 jobs:
 
 
+# Check the main folder for .json syntax / overall errors
+  validate_main:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate JSON Files - Main
+        run: |
+          cd main
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
+
+
+
+
+# Check the sharders folder for .json syntax / overall errors
+  validate_sharders:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate JSON Files - Main
+        run: |
+          cd sharders
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
+
+
+# Check the custom folder for .json syntax / overall errors
+  validate_custom:
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/txt-testing'
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate JSON Files - Main
+        run: |
+          cd custom
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
+
+
+
+
+
+# -----------------------------------------
+# Build pack
+# -----------------------------------------
+
 
 
 
@@ -24,7 +73,7 @@ jobs:
   # Build the root pack
   build_main:
     runs-on: ubuntu-latest
-
+    needs: [validate_main]
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -58,6 +107,7 @@ jobs:
   # Build the sharders pack
   build_sharders:
     runs-on: ubuntu-latest
+    needs: [validate_sharders]
 
 
     # Steps represent a sequence of tasks that will be executed as part of the job
@@ -98,7 +148,7 @@ jobs:
 # Custom texture pack - contains experimental changes / latest chagnes from txt-testing branch.
   build_custom:
     runs-on: ubuntu-latest
-    needs: [build_main, build_sharders]
+    needs: [validate_custom,build_main, build_sharders]
     if: github.ref == 'refs/heads/txt-testing'
 
 
