Implement JSON check - Public Merge

diff --git a/.github/workflows/validate_json_files.yml b/.github/workflows/validate_json_files.yml
--- a/.github/workflows/validate_json_files.yml
+++ b/.github/workflows/validate_json_files.yml
@@ -1,36 +1,34 @@
-# This is a basic workflow to help you get started with Actions
 
-name: CI
 
-# Controls when the workflow will run
+name: Check JSON Files
+
 on:
-  # Triggers the workflow on push or pull request events but only for the "txt-main" branch
   push:
     branches: [ "txt-main" ]
   pull_request:
     branches: [ "txt-main" ]
 
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  validate_main:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      # Check main folder
+      - name: Validate JSON Files - Main
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          cd main
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
+
+        # Check sharders folder  
+      - name: Validate JSON Files - Main
+        run: |
+          cd sharders
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
