Integrate script with main branch

diff --git a/.github/workflows/validate_json_files.yml b/.github/workflows/validate_json_files.yml
--- a/.github/workflows/validate_json_files.yml
+++ b/.github/workflows/validate_json_files.yml
@@ -15,9 +15,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-
-
-      # Check main folder
       - name: Validate JSON Files - Main
         run: |
           cd main
@@ -25,10 +22,32 @@ jobs:
             jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
           done
 
+
+
+
+  validate_sharders:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
         # Check sharders folder  
-      - name: Validate JSON Files - Main
+      - name: Validate JSON Files - Sharders
         run: |
           cd sharders
+          for file in $(find . -type f -name "*.json"); do
+            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
+          done
+
+
+
+  validate_custom:
+    runs-on: ubuntu-latest
+    if: github.ref == 'refs/heads/txt-testing'
+    steps:
+      - uses: actions/checkout@v3
+        # Check sharders folder  
+      - name: Validate JSON Files - Custom
+        run: |
+          cd custom
           for file in $(find . -type f -name "*.json"); do
             jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
           done
